<?php

namespace App\PowerDns\Api\Endpoint;

class CreateTSIGKey extends \Jane\OpenApiRuntime\Client\BaseEndpoint implements \Jane\OpenApiRuntime\Client\Psr7Endpoint
{
    use \Jane\OpenApiRuntime\Client\Psr7EndpointTrait;
    protected $server_id;

    /**
     * This methods add a new TSIGKey. The actual key can be generated by the server or be provided by the client
     *
     * @param string                          $serverId The id of the server
     * @param \App\PowerDns\Api\Model\TSIGKey $tsigkey  The TSIGKey to add
     */
    public function __construct(string $serverId, \App\PowerDns\Api\Model\TSIGKey $tsigkey)
    {
        $this->server_id = $serverId;
        $this->body = $tsigkey;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return str_replace(['{server_id}'], [$this->server_id], '/servers/{server_id}/tsigkeys');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return $this->getSerializedBody($serializer);
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    public function getAuthenticationScopes(): array
    {
        return ['APIKeyHeader'];
    }

    /**
     * {@inheritdoc}
     *
     * @throws \App\PowerDns\Api\Exception\CreateTSIGKeyConflictException
     * @throws \App\PowerDns\Api\Exception\CreateTSIGKeyUnprocessableEntityException
     * @throws \App\PowerDns\Api\Exception\CreateTSIGKeyInternalServerErrorException
     *
     * @return null|\App\PowerDns\Api\Model\TSIGKey
     */
    protected function transformResponseBody(string $body, int $status, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType)
    {
        if (201 === $status) {
            return $serializer->deserialize($body, 'App\\PowerDns\\Api\\Model\\TSIGKey', 'json');
        }
        if (409 === $status) {
            throw new \App\PowerDns\Api\Exception\CreateTSIGKeyConflictException($serializer->deserialize($body, 'App\\PowerDns\\Api\\Model\\Error', 'json'));
        }
        if (422 === $status) {
            throw new \App\PowerDns\Api\Exception\CreateTSIGKeyUnprocessableEntityException($serializer->deserialize($body, 'App\\PowerDns\\Api\\Model\\Error', 'json'));
        }
        if (500 === $status) {
            throw new \App\PowerDns\Api\Exception\CreateTSIGKeyInternalServerErrorException($serializer->deserialize($body, 'App\\PowerDns\\Api\\Model\\Error', 'json'));
        }
    }
}
