--- 
entities: 
  dynamicaddress: 
    actions: 
      add: 
        id: false
      edit: 
        id: true
      grid: 
        default: true
        id: false
      remove: 
        id: true
    namespace: OUTRAGEdns.DynamicAddress
    route: dynamicaddresses
    table: dynamic_addresses
    type: dynamicaddress
