entities: 
    dynamicaddressrecord: 
        actions: 
            add: 
                id: false
            edit: 
                id: true
            grid: 
                default: true
                id: false
            remove: 
                id: true
        namespace: OUTRAGEdns.DynamicAddressRecord
        table: dynamic_addresses_records
        type: dynamicaddressrecord
