--- 
entities: 
  zonetemplate: 
    actions: 
      add: 
        id: false
      edit: 
        id: true
      grid: 
        default: true
        id: false
      remove: 
        id: true
    namespace: OUTRAGEdns.ZoneTemplate
    route: templates
    table: zone_templ
    type: zonetemplate
